set(_vtk_module_import_prefix "${CMAKE_CURRENT_LIST_DIR}")
get_filename_component(_vtk_module_import_prefix "${_vtk_module_import_prefix}" DIRECTORY)
get_filename_component(_vtk_module_import_prefix "${_vtk_module_import_prefix}" DIRECTORY)
get_filename_component(_vtk_module_import_prefix "${_vtk_module_import_prefix}" DIRECTORY)
set_property(TARGET "GDCM::vtkgdcm" PROPERTY "INTERFACE_vtk_module_exclude_wrap" "FALSE")
set_property(TARGET "GDCM::vtkgdcm" PROPERTY "INTERFACE_vtk_module_depends" "VTK::CommonCore;VTK::CommonDataModel;VTK::CommonExecutionModel;VTK::IOImage;VTK::IOLegacy;VTK::ImagingSources")
set_property(TARGET "GDCM::vtkgdcm" PROPERTY "INTERFACE_vtk_module_private_depends" "VTK::CommonMisc;VTK::ImagingCore;VTK::IOCore")
set_property(TARGET "GDCM::vtkgdcm" PROPERTY "INTERFACE_vtk_module_optional_depends" "VTK::InteractionStyle;VTK::RenderingCore")
set_property(TARGET "GDCM::vtkgdcm" PROPERTY "INTERFACE_vtk_module_implements" "")
set_property(TARGET "GDCM::vtkgdcm" PROPERTY "INTERFACE_vtk_module_implementable" "FALSE")
set_property(TARGET "GDCM::vtkgdcm" PROPERTY "INTERFACE_vtk_module_library_name" "vtkgdcm")
set_property(TARGET "GDCM::vtkgdcm" PROPERTY "INTERFACE_vtk_module_headers" "${_vtk_module_import_prefix}/include/gdcm-3.0/vtk-9.1/vtkGDCMTesting.h;${_vtk_module_import_prefix}/include/gdcm-3.0/vtk-9.1/vtkGDCMImageReader.h;${_vtk_module_import_prefix}/include/gdcm-3.0/vtk-9.1/vtkGDCMImageWriter.h;${_vtk_module_import_prefix}/include/gdcm-3.0/vtk-9.1/vtkGDCMMedicalImageProperties.h;${_vtk_module_import_prefix}/include/gdcm-3.0/vtk-9.1/vtkGDCMImageReader2.h;${_vtk_module_import_prefix}/include/gdcm-3.0/vtk-9.1/vtkImageMapToWindowLevelColors2.h;${_vtk_module_import_prefix}/include/gdcm-3.0/vtk-9.1/vtkImageYBRToRGB.h;${_vtk_module_import_prefix}/include/gdcm-3.0/vtk-9.1/vtkImageRGBToYBR.h;${_vtk_module_import_prefix}/include/gdcm-3.0/vtk-9.1/vtkGDCMPolyDataReader.h;${_vtk_module_import_prefix}/include/gdcm-3.0/vtk-9.1/vtkGDCMPolyDataWriter.h;${_vtk_module_import_prefix}/include/gdcm-3.0/vtk-9.1/vtkRTStructSetProperties.h;${_vtk_module_import_prefix}/include/gdcm-3.0/vtk-9.1/vtkLookupTable16.h;${_vtk_module_import_prefix}/include/gdcm-3.0/vtk-9.1/vtkImageMapToColors16.h;${_vtk_module_import_prefix}/include/gdcm-3.0/vtk-9.1/vtkImageColorViewer.h;${_vtk_module_import_prefix}/include/gdcm-3.0/vtk-9.1/vtkGDCMThreadedImageReader2.h;${_vtk_module_import_prefix}/include/gdcm-3.0/vtk-9.1/vtkgdcmModule.h")
set_property(TARGET "GDCM::vtkgdcm" PROPERTY "INTERFACE_vtk_module_hierarchy" "${_vtk_module_import_prefix}/lib/aarch64-linux-gnu/vtk-9.1/hierarchy/vtkgdcm/vtkgdcm-hierarchy.txt")
unset(_vtk_module_import_prefix)
